version: "3.9"
services:
  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: chapi
    volumes:
      - dbdata:/var/lib/postgresql/data
    command: >
      postgres -c shared_buffers=256MB -c max_connections=50
volumes:
  dbdata:
