"""initial schema

Revision ID: 6cb55646f788
Revises: 
Create Date: 2026-07-09 10:49:44.662585
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6cb55646f788'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=16), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('ape_paterno', sa.String(length=200), nullable=False),
    sa.Column('ape_materno', sa.String(length=200), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=True),
    sa.Column('razon_social', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.String(length=200), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('fuente', sa.String(length=200), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=True),
    sa.Column('results_json_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultas_created_at'), 'consultas', ['created_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consulta_id', sa.UUID(), nullable=True),
    sa.Column('usuario', sa.String(length=200), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('sujeto', sa.Text(), nullable=False),
    sa.Column('fuente', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_consulta_id'), 'audit_logs', ['consulta_id'], unique=False)
    op.create_table('case_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consulta_id', sa.UUID(), nullable=False),
    sa.Column('competencia', sa.String(length=32), nullable=True),
    sa.Column('rit', sa.String(length=64), nullable=True),
    sa.Column('ruc', sa.String(length=64), nullable=True),
    sa.Column('tribunal', sa.String(length=300), nullable=True),
    sa.Column('caratulado', sa.Text(), nullable=True),
    sa.Column('fecha_ingreso', sa.String(length=32), nullable=True),
    sa.Column('estado', sa.String(length=120), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('litigantes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('relaciones', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('possible_homonym', sa.Boolean(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_results_consulta_id'), 'case_results', ['consulta_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consulta_id', sa.UUID(), nullable=False),
    sa.Column('html_path', sa.String(length=500), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_index(op.f('ix_case_results_consulta_id'), table_name='case_results')
    op.drop_table('case_results')
    op.drop_index(op.f('ix_audit_logs_consulta_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_consultas_created_at'), table_name='consultas')
    op.drop_table('consultas')
    op.drop_table('subjects')
    # ### end Alembic commands ###
