name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: { python-version: '3.12' }
    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint
      run: |
        pip install ruff && ruff app --output-format=github
    - name: Test import
      run: python - <<'PY'
        import importlib, sys, pathlib
        sys.path.append(str(pathlib.Path("app").absolute()))
        importlib.import_module("app.main")
        print("import OK ✔")
        PY
